name: HCS Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install jest jsdom
        
    - name: Run tests
      run: npx jest

    - name: Check HTML validity
      run: |
        npm install -g html-validator-cli
        html-validator --file=hcs-mermaid.html --verbose
